#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
'''



def PE_002(limit = 4*10**6):
    a, b = 0, 2
    while b < limit:
        a, b = b, 4 * b + a
    return (a + b - 2) / 4


if __name__ == "__main__":
    for n in range(10):
        print('4*10**'+str(2*n) + ' : ' + str(PE_002(4*10**(2*n))))
